name: TimeAnnouncer
version: 1.0.0
main: com.example.timeannouncer.TimeAnnouncer
api-version: 1.16
author: YourName
description: 在现实时间早上、中午、晚上、午夜时向玩家发送消息

commands:
  timeannouncer:
    description: 切换时间公告功能或重载配置
    usage: /timeannouncer [reload]
    permission: timeannouncer.use
    aliases: [ta]

permissions:
  timeannouncer.use:
    description: 允许使用时间公告命令
    default: true
  timeannouncer.reload:
    description: 允许重载配置文件
    default: op
  timeannouncer.receive:
    description: 允许接收时间公告消息
    default: true
